# -*- coding: utf-8 -*-
"""DA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3QFU3KRk9r1CCU2gij19xjjm4JHrL9j
"""

from sklearn.datasets import load_iris  ##iris dataset imported
import pandas as pd
import matplotlib.pyplot as plt

data = load_iris() ##dataset of iris

# Extract 'data' attr from data object, column names from attr 'feature_names'
df = pd.DataFrame(data=data['data'], columns=data['feature_names'])

# adding a col of target to the dataframe
df['target'] = data['target']

df.head()

y = df['target']
# axis=1 (or axis='columns') is vertical axis - col
# axis=0 (or axis='row') is horizontal axis - row
x = df.drop(['target'],axis=1)

x.dtypes

y.value_counts()

## Std Dev- by how much the values of a column differ from the mean value for that column

#### Compute and display summary statistics for each feature

x.describe()

#### Create a histogram for each feature

plt.hist(x['sepal length (cm)'],bins=15)
plt.show()

plt.hist(x['sepal width (cm)'],orientation='horizontal')
plt.show()

plt.hist(x['petal length (cm)'])
plt.title('Variations in petal length')
plt.xlabel('Petal length')
plt.ylabel('Frequency')
plt.show()

plt.hist(x['petal width (cm)'])
plt.show()

#### Create a combined boxplot for each feature in the dataset.

x.boxplot()